name 'custom'
maintainer 'Kapman'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Install soft for web'
long_description 'Install soft for web'
version '0.0.1'

depends 'conf', '~> 0.1.0'
depends 'apt', '~> 4.0.2'
depends 'apache2', '~> 3.2.2'
